### ISSUE TITLE
Standard Grammar

### ISSUE THREAD

**Issue by tschady** [finos-voice/voice-metadata-standard#10]
JSON is a great format for examples, but we will need to propose the schema for the standard elsewhere.

EBNF?
XML?

**Comment by leop-tcto** [comment]
@tschady I think we agree that we will be using JSON Schema. If so can we close this issue?

**Comment by vitorespindola** [comment]
It was defined to use JSON Schema in https://finosfoundation.atlassian.net/wiki/spaces/VOICE/pages/883065002/CMS-WG+Meeting+Minutes+2019-02-19
