### ISSUE TITLE
be flexible on the hashing algorithm

### ISSUE THREAD

**Issue by tschady** [finos-voice/voice-metadata-standard#13]
Hardcoding MD5 for the recording hashing algo could be more flexible.
e.g. key: algo, value: MD5.

**Comment by kemmiso** [comment]
I think allowing flexibility makes sense. We used an enum in the comchain example.  
"Type": "string"
                     "Enum": [
                        "SHA-256"
                        "SHA-384"
                        "SHA-512"
                        "SHA3-224"
                        "SHA3-256"
                        "SHA3-384"
                        "SHA3-512"

**Comment by leop-tcto** [comment]
@kemmiso this makes sense to me.

**Comment by vitorespindola** [comment]
Since #28 was merged I'm closing this.
