### ISSUE TITLE
Finance or General metadata?

### ISSUE THREAD

**Issue by tschady** [finos-voice/voice-metadata-standard#14]
Is this standard proposed for finance only or all calls?
Either way the scope should be specified in the README.

**Comment by kemmiso** [comment]
If possible I would suggest it is open. I realise a lot of the cloud 9 focus was on PWs but where we are talking about DDIs and CLI it should be open enough for other parties to adopt it.

**Comment by kemmiso** [comment]
On a similar note - one client asked us to make it more generic than just telephony. IE do we need to put call in front of things. sourceAddress, destinationAddress, comID, direction ... this way it is flexible to allow different types of channels with the same schema headings.

**Comment by vitorespindola** [comment]
A general definition will be great, if we do not limit the standard(defining finance specific fields), it will be easy to use and extend to be used on any type of voice communication record. 

BYNE's platform is used on finance and general control rooms like Utilities, Oil&Gas and Public Safety and it will be great to have the standard available for these clients as well(while keeping it compatible with the standard).

**Comment by tschady** [comment]
decision made on call Feb 19,  2019 to make the standard general.  
Industry specific terms should be values not keys.
👍

**Comment by leop-tcto** [comment]
Agreed so I am closing this issue. Thanks @tschady
